autobranch:
  pattern: '{number}-{title}</pre><script>alert(123);</script>'
  length: 60
commit:
  message:
    patterns:
      - '#[0-9]+'
approvals:
  minimum: 2
  ignore: none
  pattern: "^(:\\+1:|F44D|F44DF3FB|F44DF3FC|F44DF3FD|F44DF3FE|F44DF3FF)$"
  veto:
    pattern: "^(:\\-1:|F44E|F44EF3FB|F44EF3FC|F44EF3FD|F44EF3FE|F44EF3FF)$"
specification:
  title:
    minimum-length:
      enabled: true
      length: 8
  body:
    minimum-length:
      enabled: true
      length: 8
    contains-url: true
    contains-issue-number: true
  template:
    differs-from-body: true
pull-request:
  labels:
    additional: true
